baseURL = "https://diana-catana.github.io/"
languageCode = "en-US"
title = "Diana Catana"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Diana Catana"
  description = "This is my personal website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "diana-catana"
  Email         = "dia.catana@gmail.com"
  Twitter       = "username"
  LinkedIn      = "diana-catana-139761272"
  Stackoverflow = "username"
  Medium        = "username"
  Telegram      = "username"
  RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"


[caches]
  [caches.images]
    dir = ':cacheDir/images'
